#!/usr/bin/env python

import sys, os

VERSION = "0.01a"
__sketchdir__ = os.path.dirname(sys.argv[0])

def error(a):
	print "sketch: " + a
	sys.exit(1)

def printHelpText():
	"""Print the help text"""
	print '''Usage: sketch [OPTION]
       sketch [ACTION] [ARG1] ... [ARGn]\n
  -h, --help		print this help message
  -v, --version		print the version number and exit
  
  newproj		creates a new project
  scaffold		generates scaffolding such as models, controllers, and views
  db:migrate		migrates the database

Example:\n
  sketch newproj myapp
  sketch scaffold Post title:string body:text
  sketch db:migrate
'''

def printVersionNumber():
	"""Print the version number"""
	print "sketch " + VERSION

def newproj(name, scm=None):
	"""Create a new Sketch Project"""
	print "Creating new project: " + name
	if os.path.exists(name):
		a = ""
		while a != "y" and a != "n":
			b = "Directory %s exists. Remove it and continue? (y/n) " % name
			a = raw_input(b)
		if a == "y":
			os.system("rm -rf " + name)
		else:
			error("project creation aborted")
	os.system("tar -xvsf %s/default-project.tar.gz" % __sketchdir__)
	os.system("mv -v default-project " + name)
	
	##TODO: Add support of darcs, bzr, and other distributed scm tools
	if scm == "git":
		os.system("cd %s && git init" % name)
		os.system('''for i in $(find . -type d -regex ``./[^.].*'' -empty);
do touch $i"/.gitignore"; done''')
		os.system("cd %s && git add * && git commit -m 'first commit'" % name)
	elif scm == "hg":
		os.system("cd %s && hg init" % name)
		os.system('''for i in $(find . -type d -regex ``./[^.].*'' -empty);
do touch $i"/.hgignore"; done''')
		os.system("cd %s && hg add * && hg commit -m 'first commit'" % name
	elif scm != None:
		error("unrecognized scm: \'%s\'" % scm)
	sys.exit(1)

def scaffold(name, arguements=None):
	"""Generate the scaffolding"""
	print "Generating scaffolding for " + name
	for x in arguements:
		print x.split(":")

def main():
	cmdlen = len(sys.argv)
	if cmdlen < 2:
		error('''no action specified
Try `sketch --help\' for more information.''')
	else:
		for x in range(1, cmdlen):
			if sys.argv[x].startswith("--"):
				option = sys.argv[x][2:]
				if option == "help":
					printHelpText()
				elif option == "version":
					printVersionNumber()
				else:
					error("invalid option -- '%s'" % option)
					printHelpText()
			elif sys.argv[1].startswith("-"):
				option = sys.argv[x][1:]
				for y in option:
					if y == "h":
						printHelpText()
					elif y == "v":
						printVersionNumber()
					else:
						error("invalid option - '%s'" % y)
						printHelpText()
			else:
				action = sys.argv[x]
				if action == "newproj":
					if cmdlen > x+2:
						newproj(sys.argv[x+1], sys.argv[x+2].split(":")[1])
					elif cmdlen > x+1:
						newproj(sys.argv[x+1])
					else:
						error("missing project name")
				elif action == "scaffold":
					if cmdlen < x+1:
						error("missing model name")
					else:
						scaffold(sys.argv[x+1], sys.argv[x+2:])
						return 0
				else:
					error("unrecognized action -- '%s'" % action)
	return 0

if __name__ == '__main__': main()
